### ISSUE TITLE
Optimize the login flow

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/django-two-factor-auth#10]
Observe the image below.

![image](https://user-images.githubusercontent.com/96970/131154189-0c4487eb-a841-4623-9581-ce17fde5aa28.png)

**Tasks**

* [x] Remove "Cancel" button on initial login page.
* [x] Rename "Next" button to "Login" (or what it is in default Django admin)
* [x] Remove "Back" button everywhere.
* [ ] Inherit from the login template to prevent the menu from showing (technically not this packages problem but i think its better anyway).
* [x] Make sure the up/down arrows are not shown on the token field.
* [x] After clicking "Next" upon entering your token (with token configured) go straight to the admin (see dotted green line) instead of the auth options.

**Comment by annashamray** [comment]
@joeribekker The menu items are shown because of the `django-admin-index`. It should be adusted in the django app which uses both `2fa` and `admin_index` libs (eg.objects api)

**Comment by joeribekker** [comment]
Fixed in #11
